package com.inventory.main;

import com.inventory.dao.ProductDAO;
import com.inventory.entity.Product;
import com.inventory.entity.ProductIdentity;
import com.inventory.entity.ProductSequence;
import com.inventory.util.HibernateUtil;

import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Demonstrates different ID Generation Strategies in Hibernate
 * AUTO, IDENTITY, and SEQUENCE
 */
public class IdGenerationStrategyDemo {

    public static void main(String[] args) {
        System.out.println("====================================================");
        System.out.println("   Hibernate ID Generation Strategies Demo");
        System.out.println("====================================================\n");

        // ============================================
        // Strategy 1: AUTO (Default)
        // Hibernate chooses the best strategy based on database
        // ============================================
        System.out.println("--- Strategy 1: AUTO Generation ---");
        System.out.println("Uses GenerationType.AUTO - Hibernate chooses the strategy\n");

        Session session1 = HibernateUtil.getSessionFactory().openSession();
        Transaction tx1 = session1.beginTransaction();

        Product autoProduct1 = new Product("Laptop_Auto", "Dell XPS 15", 150000, 5);
        Product autoProduct2 = new Product("Mouse_Auto", "Logitech MX Master", 8000, 20);

        session1.save(autoProduct1);
        session1.save(autoProduct2);
        tx1.commit();

        System.out.println("Product 1 (AUTO) ID: " + autoProduct1.getId());
        System.out.println("Product 2 (AUTO) ID: " + autoProduct2.getId());
        System.out.println("Hibernate uses SEQUENCE for MySQL when AUTO is specified\n");
        session1.close();

        // ============================================
        // Strategy 2: IDENTITY
        // Database auto-increment (MySQL AUTO_INCREMENT)
        // ============================================
        System.out.println("\n--- Strategy 2: IDENTITY Generation ---");
        System.out.println("Uses GenerationType.IDENTITY - Database auto-increment\n");

        Session session2 = HibernateUtil.getSessionFactory().openSession();
        Transaction tx2 = session2.beginTransaction();

        ProductIdentity idProduct1 = new ProductIdentity("Keyboard_IDENTITY", "Corsair K70", 15000, 10);
        ProductIdentity idProduct2 = new ProductIdentity("Monitor_IDENTITY", "LG UltraWide", 45000, 8);

        session2.save(idProduct1);
        session2.save(idProduct2);
        tx2.commit();

        System.out.println("Product 1 (IDENTITY) ID: " + idProduct1.getId());
        System.out.println("Product 2 (IDENTITY) ID: " + idProduct2.getId());
        System.out.println("IDs are generated by MySQL AUTO_INCREMENT\n");
        session2.close();

        // ============================================
        // Strategy 3: SEQUENCE
        // Uses database sequence (if supported)
        // ============================================
        System.out.println("\n--- Strategy 3: SEQUENCE Generation ---");
        System.out.println("Uses GenerationType.SEQUENCE - Database sequence\n");

        Session session3 = HibernateUtil.getSessionFactory().openSession();
        Transaction tx3 = session3.beginTransaction();

        ProductSequence seqProduct1 = new ProductSequence("Headphones_SEQUENCE", "Sony WH-1000XM5", 25000, 15);
        ProductSequence seqProduct2 = new ProductSequence("Tablet_SEQUENCE", "iPad Pro 12.9", 90000, 7);

        session3.save(seqProduct1);
        session3.save(seqProduct2);
        tx3.commit();

        System.out.println("Product 1 (SEQUENCE) ID: " + seqProduct1.getId());
        System.out.println("Product 2 (SEQUENCE) ID: " + seqProduct2.getId());
        System.out.println("IDs are generated by the sequence\n");
        session3.close();

        // ============================================
        // Summary
        // ============================================
        System.out.println("\n====================================================");
        System.out.println("   ID Generation Strategy Comparison");
        System.out.println("====================================================");
        System.out.println("| Strategy | Database Support    | ID Generation |");
        System.out.println("|----------|---------------------|---------------|");
        System.out.println("| AUTO     | All databases       | Hibernate     |");
        System.out.println("| IDENTITY | MySQL, SQL Server   | Database      |");
        System.out.println("| SEQUENCE | Oracle, PostgreSQL   | Database      |");
        System.out.println("====================================================\n");

        System.out.println("For MySQL:");
        System.out.println("- AUTO typically uses SEQUENCE internally");
        System.out.println("- IDENTITY uses AUTO_INCREMENT");
        System.out.println("- SEQUENCE creates a sequence table\n");

        // Clean up
        HibernateUtil.shutdown();
    }
}

